package eka.dr.intl.assistant.utility

enum class ActionType(val stringValue: String) {
    ON_PATIENT_CLICK("ON_PATIENT_CLICK"),
    ON_VOICE_BUTTON_CLICK("ON_VOICE_BUTTON_CLICK"),
    OPEN_INPUT_BOTTOM_SHEET("OPEN_INPUT_BOTTOM_SHEET"),
    ON_VOICE_TO_RX_CONVERSATION_MODE("ON_VOICE_TO_RX_CONVERSATION_MODE"),
    ON_VOICE_TO_RX_DICTATION_MODE("ON_VOICE_TO_RX_DICTATION_MODE"),
    ON_CAMERA_CLICK("ON_CAMERA_CLICK"),
    ON_GALLERY_CLICK("ON_GALLERY_CLICK"),
    ON_VOICE_2_RX_CLICK("ON_VOICE_2_RX_CLICK"),
    START_CHAT("START_CHAT"),
    ON_BACK("ON_BACK"),
    OPEN_CLINICAL_NOTES("OPEN_CLINICAL_NOTES"),
    START_CONSULTATION("START_CONSULTATION"),
    SHOW_INPUT_BOTTOM_SHEET("SHOW_INPUT_BOTTOM_SHEET"),
    CHAT_CLICK("CHAT_CLICK"),
    ON_POSITIVE_REVIEW_CLICKED("ON_POSITIVE_REVIEW_CLICKED"),
    ON_NEGETIVE_REVIEW_CLICKED("ON_NEGETIVE_REVIEW_CLICKED"),
    ON_COPY_CLICKED("ON_COPY_CLICKED"),
    ON_SHARE_CLICKED("ON_SHARE_CLICKED"),
    ON_CHAT_MESSAGE_CLICKED("ON_CHAT_MESSAGE_CLICKED"),
}