package eka.dr.intl.common

class PageIdentifier {
    companion object {
        const val PAGE_ID = "pageId"
        const val PAGE_PARAMS = "params"
        const val PAGE_ID_HOMEPAGE = "home"
        const val PAGE_ID_WEB_VIEW = "webview"
        const val PAGE_ID_AUTH_WEB_VIEW = "auth_webview"
        const val PAGE_ID_ABHA_WEB_VIEW = "abha_webview"
        const val PAGE_ID_BOTTOM_WEB_VIEW = "bottom_webview"
        const val PAGE_ID_PRIVACY_VIEW = "privacy_view"
        const val PAGE_ID_NOTIFICATION_LIST = "msg_list"
        const val PAGE_ID_TELE = "tele"
        const val PAGE_ID_QUERY_WITH_ACTION = "tryst-query-with-action"
        const val PAGE_PLAY_STORE = "play_store"
        const val PAGE_IN_APP_REVIEW = "review"
        const val PAGE_CUSTOM_REVIEW = "custom_review"
        const val PAGE_CRISP = "crisp"
        const val PAGE_CHROME_TAB = "browser"
        const val PAGE_APPOINTMENTS = "appointments"
        const val PAGE_MEDICAL_RECORDS = "medical_records"
        const val PAGE_MEDICAL_RECORDS_WITH_UPLOAD = "medical_records_with_upload"
        const val PAGE_RECORD_DETAILS = "record_details"
        const val APP_SETTINGS = "app_settings"
        const val PAGE_ID_PATIENT_LIST = "all_patients"
        const val PAGE_CHAT_SCREEN = "chat_screen"
        const val PAGE_AI_CHAT = "chat_bot"
        const val ADD_PATIENT = "add_patient"
        const val PAGE_CONDITION_LED_SA = "conditional_sa"
        const val PAGE_SYMCHECK_SA = "symcheck_sa"
        const val PAGE_IMAGE_CROP = "image_cropping"
        const val PAGE_ID_SELF_ASSESSMENT = "self_assessment"
        const val PAGE_SA_LIST = "sa_list"
        const val PAGE_ID_SA_RESULT = "sa_result"
        const val PAGE_DEEP_THOUGHT = "deepthought_page"
        const val PAGE_DOC_PREVIEW = "doc_preview"
        const val PAGE_VOICE_TO_RX = "voice_to_rx"
        const val PAGE_VOICE_TO_RX_ONGOING = "voice2RxOngoing"
        const val PAGE_CHAT_BOT_PATIENT_SESSION = "chat_bot_patient_session"
        const val PAGE_PDF_PREVIEW_SCREEN = "pdf_preview_screen"
    }
}